name: Auto Merge and Sync Branches

on:
  push:
    branches:
      - "SW-23-client-changes"

permissions:
  contents: write

jobs:
  merge-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge feature branch to dev
        run: |
          git checkout dev
          git pull origin dev
          git merge ${{ github.ref_name }} --no-edit
          git push origin dev

      - name: Merge dev branch to main
        run: |
          git checkout main
          git pull origin main
          git merge dev --no-edit
          git push origin main
